### ISSUE TITLE
ClamXAV shows infected file in NicePlayer.app

### ISSUE THREAD

**Issue by shape55** [jbtule/NicePlayer#13]
System Infection: PUA.OSX.NicePlayer

using 0.98-rc on OSX 10.8.5

**Comment by jbtule** [comment]
I don't know, I think it's because shady stuff out there bundles niceplayer (possibly even modified) they consider it an potentially unwanted application (PUA). As long as you downloaded niceplayer from releases in this repository you are fine to ignore it. 
https://discussions.apple.com/thread/8516450

**Comment by shape55** [comment]
Gotcha – yes, I'm sure that's the case then.  I figured it was a false positive.  Thanks for the link.  I did install it from this repository, so no worries.
